# Generated by Django 5.2.8 on 2026-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplate', '0003_request_delivery_status_request_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
