# Generated by Django 5.2.8 on 2026-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplate', '0004_alter_request_latitude_alter_request_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='request',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='request',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='volunteerlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('volunteer', 'Volunteer')], max_length=20, null=True),
        ),
    ]
