# Generated by Django 5.2.8 on 2026-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplate', '0009_userprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('recipient', 'Recipient')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='VolunteerLocation',
        ),
    ]
